<?php

namespace Modules\Sale\App\Providers;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;
use Kontur\Dashboard\App\Facades\Modules;
use Kontur\Dashboard\App\Modules\Menu\MenuItem;
use Kontur\Dashboard\App\Modules\Module;
use Kontur\Dashboard\App\Modules\ModuleProvider;
use Modules\Menu\App\Facades\MenuBuilder;

class SaleModuleProvider extends ModuleProvider
{
    protected string $name = 'sale';

    protected function init(): void
    {
        // TODO: Implement init() method.
    }

    protected function run(): void
    {
        if ($this->module->isActive()) {
            MenuBuilder::add([
                new \Modules\Menu\App\Models\MenuItem([
                    'name' => settings('name', 'sale', 'Акции'),
                    'route_name' => 'sale.index',
                ])
            ], 'Модули');
        }
    }

    protected function getModule(): Module
    {
        return new Module(
            id: 'sale',
            name: settings('name', 'sale', 'Акции'),
            sidebarItems: [
                new MenuItem(
                    name: settings('name', 'sale', 'Акции'),
                    routeName: 'admin.sale.index',
                    icon: '<i class="bi bi-coin"></i>',
                )
            ],
        );
    }

    protected function getDir(): string
    {
        return __DIR__;
    }

    protected function registerResources(): void
    {
        Blade::componentNamespace('Modules\\Sale\\App\\View\\Components', 'sale');
        parent::registerResources(); // TODO: Change the autogenerated stub
    }
}
